version: "3.5"

services:
  proxy:
    image: "traefik:v2.2"
    restart: always
    command:
      # Enable API/dashboard
      - "--api=true"
      - "--api.dashboard=true"
      # Set logging level
      - "--log.level=INFO"
      # Docker provider settings
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy-public"
      # Entrypoint for HTTP trafic
      - "--entrypoints.web.address=:80"
      # Entrypoint for HTTPS trafic
      - "--entrypoints.websecure.address=:443"
      # Letsencrypt PROD settings
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=contact@davidcharbonnier.fr"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Letsencrypt STAGING settings
      - "--certificatesresolvers.letsencryptstaging.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptstaging.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptstaging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencryptstaging.acme.email=contact@davidcharbonnier.fr"
      - "--certificatesresolvers.letsencryptstaging.acme.storage=/letsencrypt/acme-staging.json"
      # TLS options
      - "--providers.file.directory=/etc/traefik/dyn"
      # Log HTTP/S requests
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/letsencrypt
      - ./conf/tls.yml:/etc/traefik/dyn/tls.yml
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy-public
    labels:
      # Redirect all HTTP trafic to HTTPS
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Enable Traefik proxy to expose API/dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`proxy.davidcharbonnier.fr`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"

volumes:
  certs:

networks:
  proxy-public:
    name: proxy-public

